packages:
  - "marketing"
  - "packages/*"
  - "apps/*"
  - "cli"
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  lightningcss: true
  '@sentry/cli': true
  workerd: true
  core-js: true
minimumReleaseAgeExclude:
  - posthog-js@1.418.11
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - lightningcss
overrides:
  vite: "^8.0.16"
